---
- name: Airflow | Install linux packages
  yum:
    name: "{{ airflow_linux_packages }}"
    state: present
    update_cache: yes

- name: Airflow | upgrade pip
  pip:
    executable: "/usr/bin/pip3"
    name: "pip"
    version: "{{ pip_version }}"
  ignore_errors: yes

- name: Airflow | Install pip packages
  pip:
    executable: "{{ pip_executable }}"
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items: "{{ pip_packages }}"